# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7885-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter universal7885-common,$(TARGET_DEVICE)),)

endif
